# Generated by Django 4.1.2 on 2022-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TheShops",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Shop create time"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name of the shop"),
                ),
                ("text", models.TextField(verbose_name="Content of the shop")),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Shop update time"
                    ),
                ),
                (
                    "verification",
                    models.BooleanField(
                        default=False, verbose_name="Verification status of shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "The shop",
                "verbose_name_plural": "The shops",
                "db_table": "the_shops",
                "ordering": ["id"],
            },
        ),
    ]
